### ISSUE TITLE
Documentation error on PuppetForge

### ISSUE THREAD

**Issue by threepistons** [leoarnold/puppet-cups#18]
The Hiera example in https://forge.puppet.com/leoarnold/cups#using-hiera says:
``` yaml
---
cups::default_queue: 'GroundFloor'
cups::hiera: priority
cups_queue:
  'Office':
    ensure: 'printer'
    uri: 'lpd://192.168.2.105/binary_p1'
  'GroundFloor':
    ensure: 'class'
    members: ['Office', 'Warehouse']
```

It should probably say:
``` yaml
---
cups::default_queue: 'GroundFloor'
cups::hiera: priority
cups::resources:
  'Office':
    ensure: 'printer'
    uri: 'lpd://192.168.2.105/binary_p1'
  'GroundFloor':
    ensure: 'class'
    members: ['Office', 'Warehouse']
```

substituting **cups_queue** with **cups::resources**.
