### ISSUE TITLE
Feature request: take printers as argument rather than explicit hiera lookup

### ISSUE THREAD

**Issue by jcpunk** [leoarnold/puppet-cups#2]
I very much appreciate your hiera integration.  With Puppet 3, a hiera look up is automatic.

I'm looking to drive this from an ENC rather than hiera.  Can the hiera lookups be switched to class parameters (around https://github.com/leoarnold/puppet-cups/blob/master/manifests/init.pp#L55 ) so that I can pass them in via my ENC?

This would provide me significantly cleaner integration while not breaking existing hiera users.

Thoughts?

(relevant link: https://docs.puppet.com/hiera/1/puppet.html#automatic-parameter-lookup)

**Comment by jcpunk** [comment]
Similar behavior example: https://github.com/yo61/puppet-logrotate/blob/master/manifests/init.pp (follow rules parameter)

**Comment by leoarnold** [comment]
@jcpunk I see your point, so let's discuss this to find the best solution:

I think that Puppet's desired code style would be, that all resources be encapsulated in classes and ENC/Hiera only decide, which classes to load. So you would have classes like `myprinters::Office`, `myprinters::BackOffice` and `myprinters::Warehouse` each wrapping its own `cups_queue` resource and dependencies. These classes would then be individually loaded on each node.

Of course this becomes unreasonably complicated if you need to set different properties (`options`, `access`, ...) on different nodes. Is that the case?

**Comment by jcpunk** [comment]
Modules like saz/rsyslog, arioch/keepalived, yo61/logrotate, and ghoneycutt/hosts (Puppet Approved) seem to directly enable resource definition off of init.pp

Of those, logrotate is probably the "most similar" to cups, though maybe keepalived is close.

From the ENC side, setting different options per host isn't too bad.  The YAML output of my internal sasl class was fairly easy to customize:
```
  sasl_applications:
    settings:
      smtpd:
        mech_list:
        - plain
        - login
        pwcheck_method: auxprop
        auxprop_plugin: sasldb
        sasldb_path: /etc/postfix/passwd.db
```

Foreman lets me mix in additional "settings" based on a variety of conditions and have cascading overrides in a fairly clear manner.  This also provides a further - very clean - layer of abstraction for system state review.  It really looks like it just makes up a hiera file for each host somewhat dynamically.

"How is postfix auth configured on this host?"  I don't have to open up any classes to see the specific settings I care about.

I envision something along the lines of:
````
---
cups:
  default_queue: Office
  queues:
    Office:
      ensure: printer
      uri: lpd://192.168.2.105/binary_p1
    GroundFloor:
      ensure: class
      members:
        - Office
        - Warehouse
````
where queues is a hash that runs create_resources.  This looks fairly clean in hiera and would also be ENC friendly.

Thoughts?

**Comment by leoarnold** [comment]
Please try the following. If it solves your problem, I will merge it.

Manually add the manifest

```puppet
# MODULEPATH/cups/manifests/resources.pp
class cups::resources (
  $resources = undef
) {
  
  unless ($resources == undef) {
    validate_hash($resources)
    create_resources('cups_queue', $resources)
  }
  
}
```

and adjust your setup to

```yaml
---
cups:
  default_queue: Office
cups::resources: # This line will later become optional
  resources:
    Office:
      ensure: printer
      uri: lpd://192.168.2.105/binary_p1
    GroundFloor:
      ensure: class
      members:
        - Office
        - Warehouse
```

By the way: May I pride myself that FermiLab is using my module?
